export * from './HomePage'
export * from './PricingPage'
export * from './DocsPage'
export * from './TermsPage'
export * from './PrivacyPage'
export * from './NotFoundPage'

export * from './LoginPage'
export * from './LogoutPage'
export * from './SignupPage'
export * from './CheckoutPage'

export * from './CatchAllPage'
export * from './SmtpProxiesPage'
export * from './DashboardPage'
export * from './AccountPage'
